#!/usr/bin/env bash

export HF_HOME=$HOME/dev/.cache/huggingface
export PYTHONPATH=$(pwd)

venv/bin/python3 dev --prompt "Extreme closeup portrait of an angry day of the dead model against a wall of colorful flowers" --seed 0 --cfg 5
